# Build stage
FROM node:18 AS build
WORKDIR /app

# Install yarn if not included (usually it's included in node image)
RUN npm install -g yarn

COPY package*.json ./
COPY yarn.lock ./
RUN yarn install

COPY . .
RUN yarn build --configuration Production

# Production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]